server:
  port: 7001
eureka:
  instance:
    hostname: eureka01
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka02:7002/eureka/
  server:
    # 关闭自我保护机制
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000

