server:
  port: 8002


spring:
  application:
    name: cloud-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: '000000'



mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
logging:
  group:
    group1: com.mybatisflex,com.atguigu.order.client.PaymentService
  level:
    group1: debug
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/
  instance:
    instance-id: order8002
    prefer-ip-address: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000