server:
  port: 8001


spring:
  application:
    name: cloud-payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: '000000'
  cloud:
    zookeeper:
      connect-string: node01:2181,node02:2181,node03:2181/cloud


mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
logging:
  group:
    group1: com.mybatisflex,com.atguigu.payment.mapper
  level:
    group1: debug



